# Generated by Django 6.0.1 on 2026-01-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.CharField(default='', max_length=255),
        ),
    ]
